// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
        return ios;

      case TargetPlatform.macOS:
        return macos;

      case TargetPlatform.windows:
        return windows;

      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbUh7EHWoHJv7jrrEij3Acs1Hr1Tg7jmE',
    appId: '1:452345325632:web:11d4a06f62b0d68d7897a5',
    messagingSenderId: '452345325632',
    projectId: 'smart-flight-reservation',
    authDomain: 'smart-flight-reservation.firebaseapp.com',
    storageBucket: 'smart-flight-reservation.firebasestorage.app',
    measurementId: 'G-Z7Q8WML0Z9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg-rYJsKKi1scNecU3iVgKpQNyDSudTew',
    appId: '1:452345325632:android:16e385e1a8bc0c0d7897a5',
    messagingSenderId: '452345325632',
    projectId: 'smart-flight-reservation',
    storageBucket: 'smart-flight-reservation.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtrGxeqM3XcBtsmz0GQIV9etQDB36RLPI',
    appId: '1:452345325632:ios:5cf4f137854d8c367897a5',
    messagingSenderId: '452345325632',
    projectId: 'smart-flight-reservation',
    storageBucket: 'smart-flight-reservation.firebasestorage.app',
    iosBundleId: 'com.example.smartFlightReservation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtrGxeqM3XcBtsmz0GQIV9etQDB36RLPI',
    appId: '1:452345325632:ios:5cf4f137854d8c367897a5',
    messagingSenderId: '452345325632',
    projectId: 'smart-flight-reservation',
    storageBucket: 'smart-flight-reservation.firebasestorage.app',
    iosBundleId: 'com.example.smartFlightReservation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbUh7EHWoHJv7jrrEij3Acs1Hr1Tg7jmE',
    appId: '1:452345325632:web:16cd5d43d1fd8da47897a5',
    messagingSenderId: '452345325632',
    projectId: 'smart-flight-reservation',
    authDomain: 'smart-flight-reservation.firebaseapp.com',
    storageBucket: 'smart-flight-reservation.firebasestorage.app',
    measurementId: 'G-CP3NVXBZJ3',
  );
}